version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql_container_todolist
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolist
    ports:
      - "3306:3306"
    volumes:
      - todolist_data:/var/lib/mysql
volumes:
  todolist_data: