server:
  error:
    include-stacktrace: always


spring:
  application:
    name: backend-todolist
  datasource:
    url: jdbc:mysql://localhost:3306/todolist
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update