server:
  error:
    include-stacktrace: always

application:
  jwt:
    secretKey: password
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 1

spring:
  application:
    name: backend-todolist
  datasource:
    url: jdbc:mysql://localhost:3306/todolisttest
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update